# Generated by Django 4.1 on 2025-05-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Obstetrician-gynecologist', 'Obstetrician-gynecologist'), ('Psychiatrist', 'Psychiatrist'), ('Urologist', 'Urologist'), ('Family physician', 'Family physician'), ('Dentist', 'Dentist'), ('Geriatrician', 'Geriatrician')], max_length=100)),
                ('doctor', models.CharField(choices=[('Dr.Vinita sing', 'Dr.Vinita sing'), ('Dr.Ashu Sharma', 'Dr.Ashu Sharma'), ('Dr.Mukesh Kumar', 'Dr.Mukesh Kumar'), ('Dr.Sudhdha sharma', 'Dr.Sudhdha sharma'), ('Dr. Manish Jain', 'Dr. Manish Jain'), ('Dr.Rachana Gupta', 'Dr.Rachana Gupta'), ('Dr.Kuldeep Rajput ', 'Dr.Kuldeep Rajput'), ('Dr.Janvi Kindarkhediya', 'Dr.Janvi Kindarkhediya')], max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
